# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c7eb248f83cc5267f83ef3f40bc8180140ea8f7d87193de6ad582d5d79bb7bb35cce953f560be1f934cd29844dfca5f2abbc79d7dd7a5772833b607fd4d2617

test:
  secret_key_base: 00bc07c01cff46811074a654b8655685acb0bc04d0c63431cb5c2168dba13aaa8a4166c0fb43dbbc012489cbeea8a37bc6998724a3cf86cbe996c9d92d84ed60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
